# Generated by Django 3.1 on 2021-02-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gratitude', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gratitude_list',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
