# Generated by Django 3.1 on 2021-03-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gratitude', '0003_auto_20210224_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='gratitude_list',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
