# Generated by Django 3.1 on 2021-03-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gratitude', '0004_gratitude_list_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gratitude_list',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
