# Generated by Django 3.1 on 2021-02-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_richtextarticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testArticle',
        ),
    ]
