# Generated by Django 3.1 on 2021-03-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_remove_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
