# Generated by Django 3.1 on 2021-03-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0014_auto_20210311_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.IntegerField(choices=[(1, 'Article'), (2, 'Creativity'), (3, 'Diary'), (4, 'Journal'), (5, 'Knowledge')], unique=True),
        ),
    ]
