# Generated by Django 3.1 on 2021-03-11 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0017_auto_20210311_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, to='diary.category'),
        ),
    ]
