# Generated by Django 3.1 on 2021-03-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0020_auto_20210316_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('1', 'Article'), ('2', 'Creativity'), ('3', 'Diary'), ('4', 'Journal'), ('5', 'Knowledge'), ('6', 'Value')], default='1', max_length=25, unique=True),
        ),
    ]
