# Generated by Django 3.1 on 2021-01-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210123_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(default='Not Provided', max_length=25),
        ),
    ]
