# Generated by Django 3.1 on 2021-01-25 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210125_1918'),
        ('task', '0004_auto_20210125_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
