# Generated by Django 3.1 on 2021-01-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20210125_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(default='25-01-2021'),
        ),
    ]
