# Generated by Django 3.1 on 2021-02-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20210125_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(default='2021-02-02'),
        ),
    ]
