# Generated by Django 3.1 on 2021-02-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20210202_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(default='2021-02-21'),
        ),
    ]
