# Generated by Django 3.1 on 2021-01-20 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Physical Health', 'Physical Health'), ('Mental Health', 'Mental Health'), ('Family', 'Family'), ('Money', 'Money'), ('Career', 'Career'), ('Friends', 'Friends'), ('Education Goals', 'Education Goals'), ('Time Outside Of Work', 'Time Outside Of Work')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('topic_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='value.category')),
            ],
        ),
    ]
