# Generated by Django 3.1 on 2021-01-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('value', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Physical Health', 'Physical Health'), ('Mental Health', 'Mental Health'), ('Family', 'Family'), ('Money', 'Money'), ('Career', 'Career'), ('Friends', 'Friends'), ('Education Goals', 'Education Goals'), ('Time Outside Of Work', 'Time Outside Of Work')], max_length=50, unique=True),
        ),
    ]
