# Generated by Django 3.1 on 2021-01-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('value', '0002_auto_20210121_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='header',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
