# Generated by Django 3.1 on 2021-01-21 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('value', '0004_degree_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_major', to='value.degree'),
        ),
    ]
