# Generated by Django 3.1 on 2021-01-21 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('value', '0005_auto_20210121_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='text',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_category',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='value.category'),
        ),
        migrations.AddField(
            model_name='topic',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='header',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
